services:
  openresty:
    build: 
      context: .
      dockerfile: dockerfile
    env_file:
    - .env
    image: openresty/openresty:latest
    container_name: openresty-container
    ports:
      - "8080:80"
    depends_on:
      - postgres-container
      - redis-container
    networks:
      - backend
  postgres-container:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
    - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
    networks:
      - backend
  redis-container:
    image: redis:7
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

volumes:
  pgdata:
  redis-data:

networks:
  backend:
    driver: bridge
